project:
  type: website
  output-dir: "docs"
    
website:
  title: "Christopher T. Kenny"
  navbar:
    right:
      - text: "Research"
        href: research.html
      - text: "Software"
        href: software.html
      - text: "CV"
        href: CV.html
      - text: "Blog"
        href: blog.html
      - icon: twitter
        href: https://twitter.com/Chris_T_Kenny
      - text: "{{< iconify fa6-brands square-threads >}}"
        href: https://www.threads.net/@chris_t_kenny
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/chriskenny.bsky.social
      - icon: github
        href: https://github.com/christopherkenny
      - text: "{{< iconify fa6-brands orcid >}}"
        href: https://orcid.org/0000-0002-9386-6860
      - text: "{{< iconify fa6-brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=uVUhHXAAAAAJ
      - icon: rocket-takeoff-fill
        href: https://christopherkenny.r-universe.dev/builds
    background: "#B3001B"
  google-analytics: "G-PBRM1BV0GG"
  site-url: https://christophertkenny.com
  description: "Christopher T. Kenny's Personal Website"


format:
  html:
    theme: yeti
    sidebar: false
